
###############################################################################
# copy this file and rename it to "Makefile.config" and edit it to your needs
#
# this file is included by "Makefile" and "testbench.sh"
###############################################################################

# should point to the directory contain VICE x64 binary.
# if you have checked out "trunk" and "testprogs" into the same directory AND
# built the VICE binaries in-tree, you may leave this empty to use these 
# binaries.
VICEDIR="/usr/bin"
EMUDIR="../../sim/c64/"

# should point to the directory containing hoxs64
HOXS64DIR="~/c64stuff/hoxs64/"

# should point to directoy containing z64k
Z64KDIR="~/c64stuff/z64k/"

# should point to directoy containing micro64
MICRO64DIR="~/c64stuff/micro64/"

# should point to directoy containing YACE
YACEDIR="~/c64stuff/yace/"

# should point to directoy containing emu64
EMU64DIR="~/c64stuff/emu64/"

# should point to directoy containing denise
DENISEDIR="~/c64stuff/denise/"

# should point to the directory containing kernal64
KERNAL64DIR="~/c64stuff/kernal64/"

# the IP used for the U64 remote interface
U64IP="192.168.100.210"
